### ISSUE TITLE
Create "Household Members" Schema

### ISSUE THREAD

**Issue by hopieyimmie** [hack4impact-calpoly/five-cities-food-pantry#37]
**Description**
A client is the head of the household. If they have household members, they are stored as a string array. Each household member has information on them and also checks to see if they are an adult or child. Create a schema that's connected to the client schema so in the Client page their information appears.
 
**Acceptance Criteria**
- firstName : Str
- lastName : Str
- birthDate : Date
- isAdult : Boolean
- headHousehold : Client ID (connects to the main client and use MongoDB unique ID)

**Additional Information**
Here is the schema layout 
<img width="400" alt="Screen Shot 2024-03-09 at 9 50 59 PM" src="https://github.com/hack4impact-calpoly/five-cities-food-pantry/assets/47905779/af0264ae-4ddf-4a73-9746-1d9c6dffa0b6">

**Comment by ajesus7** [comment]
hi! I'm working on the AuthorizedMembers schema and I thought it might make more sense to have it be named "AuthorizedMembers" instead of "Authorized_members" to better match the naming convention that we currently have". So, I changed the ObjectId reference within the clientSchema to reference "HouseholdMember". Are you able to define your schema to be titled "HouseholdMember" too? Thanks!
